import type { PeerProofPayload, PeerExecutionBinding, PeerRunPayload, PeerRunRequest, PeerRunDelivery } from "../generated/typescript/peer.js";
export const peerProofLifetimeSeconds: number;
export const peerProofClockSkewSeconds: number;
export const peerInvitationMaximumSeconds: number;
export const peerSettlementMaximumSeconds: number;
export function peerDigest(value: unknown): string;
export function peerRunRequestDigest(binding: PeerExecutionBinding, payload: PeerRunPayload): string;
export function verifyPeerRunRequest(request: PeerRunRequest): void;
export function peerRunDeliveryReceiptDigest(delivery: PeerRunDelivery): string;
export function peerProofTranscript(payload: PeerProofPayload): Uint8Array;
export function peerProofTimeValid(payload: PeerProofPayload, now: number): boolean;
